name: add report to GitHub pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
        env:
          BASE_URL: ${{secrets.BASE_URL}}
         
      - name: Run tests and generate report in Docker
        env:
          BASE_URL: ${{secrets.BASE_URL}}
        run: |
          docker compose up
      
      - name: Prepare report for GitHub Pages
        run: |
          mkdir -p public/allure-report
          cp -r allure-report/* public/allure-report/ || echo "No report generated"
      
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/allure-report
          publish_branch: gh-pages
          force_orphan: true