name: add report to GitHub pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   BASE_URL: "https://telnyx.com/"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: run tests
        run: npm run test
        env:
          BASE_URL: ${{secrets.BASE_URL}}

      - name: Install Allure
        run: npm install -D allure-commandline

      - name: Generate Allure report
        run: |
          npm run allure:generate
          mkdir -p public/allure-report
          mv allure-report/* public/allure-report/

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/allure-report
          publish_branch: gh-pages
          force_orphan: true
